### ISSUE TITLE
Optimize pre-computed table lookup

### ISSUE THREAD

**Issue by zknoname** [zknoname/pedersen-hash-solidity#1]
At the moment, we have 64 tables of 256 precomputed EC points.
The hash function lookups one point in each table and adds them together.

I generated code for the lookup tables but it seems very inefficient (1m9 gas).

Is there any known implementation of such lookup tables in an gas efficient manner ?

**Comment by microbecode** [comment]
If I'm looking at the right code, you are recreating the table every time the function is called. Could you create it upon deployment? Or if that takes too much gas, add separate functions to store it in the contract state and the `get` method then just accesses the state.

**Comment by zknoname** [comment]
> If I'm looking at the right code, you are recreating the table every time the function is called. Could you create it upon deployment? Or if that takes too much gas, add separate functions to store it in the contract state and the `get` method then just accesses the state.

I'll try that. I thought that using only memory would be less costly than using storage.
I'm still looking for implementation of some sort of "data storage" in Solidity contracts in the mean time.

**Comment by microbecode** [comment]
Well, in a sense it is cheaper, but you are shifting the cost from "pay a bigger amount once, upon deployment" to "pay a smaller amount every single time the `get` function is called". Paying bigger amount in deployment will save you a lot of gas in subsequent calls.

**Comment by zknoname** [comment]
> Well, in a sense it is cheaper, but you are shifting the cost from "pay a bigger amount once, upon deployment" to "pay a smaller amount every single time the `get` function is called". Paying bigger amount in deployment will save you a lot of gas in subsequent calls.

I implemented it in commit  [b6772fc](https://github.com/zknoname/pedersen-hash-solidity/commit/b6772fcbc1faef4e2b8af7f04af04c6b70a86013)

Gas is ~800k for one hash
